version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: steel_db
    ports:
      - "5433:5432"  # Map the container's PostgreSQL port (5432) to host's port 5433
    networks:
      - steel_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: steel_db
    ports:
      - "27018:27017"  # Map the container's MongoDB port (27017) to host's port 27018
    networks:
      - steel_network
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    networks:
      - steel_network
    environment:
      NODE_ENV: development
      PG_HOST: postgres
      PG_USER: user
      PG_PASSWORD: password
      PG_DATABASE: steel_db
      MONGO_URL: mongodb://root:rootpassword@mongo:27018/steel_db?authSource=admin

networks:
  steel_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
